server:
  port: 7002
eureka:
  instance:
    #hostname: localhost #eureka服务端实例名称
    hostname: eureka7002.com #eureka服务端实例名称
  client:
    register-with-eureka: false #表示不向注册中心注册自己
    fetch-registry: false #false表示自己就是注册中心，我的职责就是维护服务实例,并不区检索服务
    service-url:
      #defaultZone: http://:${server.port}/eureka/${eureka.instance.hostname}
      #集群：相互注册，互相守护
      defaultZone: http://eureka7001.com:7001/eureka/