#端口号
server:
  port: 9527
#项目名
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心创建动态路由的方式
      routes:
        - id: payment_route # 路由的id,没有规定规则但要求唯一,建议配合服务名
        #匹配后提供服务的路由地址
          #uri: http://localhost:8003
          uri: lb://CLOUD-PAYMENT-SERVICE #lb表示开启负载均衡
          predicates:
          - Path=/payment/get/** # 断言，路径相匹配的进行路由
        - id: payment_route2
          #uri: http://localhost:8003
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
          - Path=/payment/lb/** #断言,路径相匹配的进行路由

#eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
